### PR TITLE
added credentialed smtp server connect, changed default hostname, por…

### PR DESCRIPTION
**Pull request by KyleEvers**
…t, and from address

### CODE REVIEW

**Review by KyleEvers — COMMENTED** [review]
I agree that it should default to ncats box and not reports for support and CC.

**Review by KyleEvers — COMMENTED** [review]
Upon further inspection the first "ehlo" call was not needed. I verified this in the the documentation and test code. The rest of the code clean up looks good.

**Review by KyleEvers — COMMENTED** [review]
Good catch.

**Review by jsf9k — APPROVED** [review]
We should still be using `ncats@hq.dhs.gov` as the email address that folks reply to, the forward address for the summary report, and the CC address.  I reverted those changes.

I also cleaned up the CLI code a little bit, and now I'm happy with the changes.

Strong work, @KyleEvers!

**Pull request merged**
